wandb_name: nist20_inchikey_graff_s0
wandb_group: nist20_inchikey_graff
seed: 43
spec_fp: data/proc/nist20_qtof_cid_safe19659/spec_df.pkl
mol_fp: data/proc/nist20_qtof_cid_safe19659/mol_df.pkl
split_dp: data/split/nist20_qtof_cid_safe19659_scaffold60_20_20_seed42
ann_fp: data/proc/nist20_qtof_cid_safe19659/ann_df_magma_fragbits_graff_nonempty.pkl
frag_params:
  pyg: false
spec_params:
  merge: false
  nce: false
  merge_keep_ces: false
  preprocess: true
  prec_type: true
  prec_type_str: false
  prec_types:
  - '[M+H]+'
  inst_type: true
  inst_types:
  - QTOF
  prec_mz: true
  prec_mass_diff: true
  ace: true
  sparse: true
  unique_id: true
  counts: true
mol_params:
  pyg: false
  graff: true
  preprocess: true
ann_params:
  max_isotope: 2
  library_size: 15000
  num_eigs: 8
  filter_peaks: false
  filter_peaks_tol: 0.02
  library_splits:
  - train
  huge_mz_diff_threshold: null
  big_mz_diff_ppm_threshold: null
  preprocess: true
  library_fp: null
model_type: graff
graff_encoder_dim: 1024
graff_decoder_dim: 1024
graff_encoder_depth: 6
graff_decoder_depth: 2
graff_eig_dim: 32
graff_eig_depth: 2
graff_dropout: 0.0
graff_min_probability: 0.0
graff_min_mz: 0.0
ce_insert_type: embed
ce_insert_location: mlp
ce_insert_merge: false
loss_type: cross_entropy
output_distribution: peak_marginal
sparse_cosine_similarity: true
oos_loss: false
skip_extra_losses: true
predict_oos: false
oos_tolerance_multiple: 1
gaussian_renormalize: true
pm_tolerance_multiple: 1
train_batch_size: 16
eval_batch_size: 16
accumulate_grad_batches: 1
gradient_clip_val: 5.0
lr: 0.000254
weight_decay: 1.0e-06
accelerator: gpu
devices: 1
min_epochs: 1
max_epochs: 30
lr_schedule: true
lr_decay_rate: 0.74
lr_warmup_steps: 1000
lr_decay_steps: 5000
debug_overfit: false
upload_checkpoints: true
checkpoint_metric: val_cos_sim_0.01_epoch/mean
auxiliary_scores:
- cos_sim
eval_mz_bin_res:
- 0.01
precision: 32
use_tensor_float32: true
automatic_optimization: true
compile: false
mz_bin_res: 0.01
checkpoint_metric_mode: max
eval_test_split: true
num_workers: 0
pin_memory: false
